In [2]:
import pandas as pd
from pathlib import Path

In [3]:
RAW = Path("..") / "data" / "raw"

In [4]:
def raw_path(name):
    return next(RAW.rglob(f"yelp_academic_dataset_{name}.json"))

In [5]:
business = pd.read_json(raw_path("business"), lines=True, dtype=False, convert_dates=False)
business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",NaN
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [6]:
business.info()

<class 'pandas.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  str
 1   name          150346 non-null  str
 2   address       150346 non-null  str
 3   city          150346 non-null  str
 4   state         150346 non-null  str
 5   postal_code   150346 non-null  str
 6   latitude      150346 non-null  float64
 7   longitude     150346 non-null  float64
 8   stars         150346 non-null  float64
 9   review_count  150346 non-null  int64
 10  is_open       150346 non-null  int64
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  str
 13  hours         127123 non-null  object
dtypes: float64(3), int64(2), object(2), str(7)
memory usage: 16.1+ MB

In [7]:
business["attributes"].iloc[0]

{'ByAppointmentOnly': 'True'}

In [23]:
business['categories'].dropna().str.split(",").explode().value_counts().head(20)

categories
 Restaurants                  36978
 Food                         20998
 Shopping                     18915
Restaurants                   15290
 Home Services                10563
 Nightlife                     9990
 Beauty & Spas                 9907
 Bars                          9130
 Health & Medical              8832
 Local Services                8556
 Event Planning & Services     7828
 Automotive                    7324
Food                           6783
 Sandwiches                    6645
 American (Traditional)        6504
 Active Life                   5768
Shopping                       5480
 Coffee & Tea                  5153
 Breakfast & Brunch            5110
 Fast Food                     5073
Name: count, dtype: int64

In [20]:
business["city"].value_counts().head(10)

city
Philadelphia     14569
Tucson            9250
Tampa             9050
Indianapolis      7540
Nashville         6971
New Orleans       6209
Reno              5935
Edmonton          5054
Saint Louis       4827
Santa Barbara     3829
Name: count, dtype: int64

In [24]:
business["stars"].value_counts().sort_index()

stars
1.0     1986
1.5     4932
2.0     9527
2.5    14316
3.0    18453
3.5    26519
4.0    31125
4.5    27181
5.0    16307
Name: count, dtype: int64

In [27]:
business["review_count"].value_counts().sort_index()

review_count
5       14921
6       11673
7        9594
8        8040
9        6875
        ...
5193        1
5721        1
6093        1
7400        1
7568        1
Name: count, Length: 1158, dtype: int64

In [29]:
business["state"]

0         CA
1         MO
2         AZ
3         PA
4         PA
          ..
150341    AB
150342    TN
150343    IN
150344    IL
150345    FL
Name: state, Length: 150346, dtype: str

In [33]:
reviews = pd.read_json(raw_path("review"), lines=True, nrows=50_000, dtype=False, convert_dates=False)

In [34]:
reviews.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

In [40]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    50000 non-null  str
 1   user_id      50000 non-null  str
 2   business_id  50000 non-null  str
 3   stars        50000 non-null  float64
 4   useful       50000 non-null  int64
 5   funny        50000 non-null  int64
 6   cool         50000 non-null  int64
 7   text         50000 non-null  str
 8   date         50000 non-null  str
dtypes: float64(1), int64(3), str(5)
memory usage: 3.4 MB

In [31]:
reviews["stars"].value_counts().sort_index()

stars
1.0     5379
2.0     4003
3.0     5677
4.0    12721
5.0    22220
Name: count, dtype: int64

In [32]:
reviews["text"].str.len().describe()

count    50000.000000
mean       546.992180
std        499.267814
min          3.000000
25%        225.000000
50%        393.000000
75%        693.000000
max       4997.000000
Name: text, dtype: float64

In [35]:
checkin = pd.read_json(raw_path("checkin"), lines=True, nrows=5, dtype=False, convert_dates=False)

In [36]:
checkin.head()

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22
3  --7PUidqRWpRSpXebiyxTg  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012...
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014...

In [38]:
print(checkin["date"].iloc[0][:200])

2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020-07-24 22:42:27, 2020-10-24 21:36:13, 2020-12-09 21:23:33, 2021-01-20 17:34:57, 2021-04-30 21:02:03, 2021-05-25 21:16:54, 2021-08-06 21:08:08, 2021-10-02